In [1]:
import numpy as np
import pandas as pd
import pickle
import matplotlib as plt  
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [2]:
df = pd.read_csv("crop_dataset.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Temperature (°C)      1000 non-null   float64
 1   Rainfall (mm)         1000 non-null   float64
 2   Humidity (%)          1000 non-null   float64
 3   Soil Type             1000 non-null   object
 4   Weather Condition     1000 non-null   object
 5   Crop Type             1000 non-null   object
 6   Yield (tons/hectare)  1000 non-null   float64
dtypes: float64(4), object(3)
memory usage: 54.8+ KB

In [3]:
print(df["Soil Type"].value_counts()) 
print()
print(df["Weather Condition"].value_counts()) 
print()
print(df["Crop Type"].value_counts()) 
print()
print(df["Yield (tons/hectare)"].value_counts()) 
print()

Soil Type
Sandy    208
Loamy    204
Peaty    203
Clay     197
Silty    188
Name: count, dtype: int64

Weather Condition
Rainy     258
Stormy    258
Cloudy    256
Sunny     228
Name: count, dtype: int64

Crop Type
Rice        228
Wheat       203
Soybeans    199
Corn        189
Barley      181
Name: count, dtype: int64

Yield (tons/hectare)
2.818937    1
8.014166    1
9.249868    1
7.947481    1
6.262616    1
           ..
6.822771    1
7.820291    1
2.921246    1
6.705009    1
7.335726    1
Name: count, Length: 1000, dtype: int64

In [4]:
df = df.rename(columns={
  "Temperature (°C)":"temperature",
  "Rainfall (mm)":"rainfall",
  "Humidity (%)":"humidity",
  "Soil Type":"soil_type",
  "Weather Condition":"weather_condition",
  "Crop Type":"crop_type",
  "Yield (tons/hectare)":"yield"
})

In [5]:
X = df.drop("yield", axis=1)
y = df["yield"]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
X_train

     temperature    rainfall   humidity soil_type weather_condition crop_type
29     15.929008  828.915474  72.708730     Peaty             Sunny     Wheat
535    33.895315  121.886093  81.707230     Peaty             Rainy      Rice
695    27.212401   68.172309  65.951614      Clay            Stormy     Wheat
557    15.575654  411.028470  54.978284     Sandy            Stormy     Wheat
836    33.296918  128.095746  89.662751     Loamy            Cloudy      Corn
..           ...         ...        ...       ...               ...       ...
106    23.207658  396.242019  82.858963     Sandy             Rainy      Corn
270    31.187223  694.981886  45.211240      Clay            Stormy      Corn
860    30.510552  776.447446  83.338518      Clay            Cloudy    Barley
435    29.019383   29.973590  59.474095      Clay             Sunny    Barley
102    21.287120  883.785885  47.897741     Loamy             Rainy      Corn

[800 rows x 6 columns]

In [8]:
X_train_OHE = pd.get_dummies(X_train, columns=["soil_type", "weather_condition", "crop_type"], drop_first=True)
X_test_OHE = pd.get_dummies(X_test, columns=["soil_type", "weather_condition", "crop_type"], drop_first=True)

In [9]:
with open("OHE.pkl","wb") as f:
  pickle.dump(X_train_OHE, f)
with open("OHE.pkl","rb") as f:
  loaded_encoder_OHE = pickle.load(f)

In [10]:
loaded_encoder_OHE

,temperature,rainfall,humidity,soil_type_Loamy,soil_type_Peaty,soil_type_Sandy,soil_type_Silty,weather_condition_Rainy,weather_condition_Stormy,weather_condition_Sunny,crop_type_Corn,crop_type_Rice,crop_type_Soybeans,crop_type_Wheat
29,15.929008,828.915474,72.708730,False,True,False,False,False,False,True,False,False,False,True
535,33.895315,121.886093,81.707230,False,True,False,False,True,False,False,False,True,False,False
695,27.212401,68.172309,65.951614,False,False,False,False,False,True,False,False,False,False,True
557,15.575654,411.028470,54.978284,False,False,True,False,False,True,False,False,False,False,True
836,33.296918,128.095746,89.662751,True,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,23.207658,396.242019,82.858963,False,False,True,False,True,False,False,True,False,False,False
270,31.187223,694.981886,45.211240,False,False,False,False,False,True,False,True,False,False,False
860,30.510552,776.447446,83.338518,False,False,False,False,False,False,False,False,False,False,False
435,29.019383,29.973590,59.474095,False,False,False,False,False,False,True,False,False,False,False
102,21.287120,883.785885,47.897741,True,False,False,False,True,False,False,True,False,False,False

In [11]:
X_train_OHE

,temperature,rainfall,humidity,soil_type_Loamy,soil_type_Peaty,soil_type_Sandy,soil_type_Silty,weather_condition_Rainy,weather_condition_Stormy,weather_condition_Sunny,crop_type_Corn,crop_type_Rice,crop_type_Soybeans,crop_type_Wheat
29,15.929008,828.915474,72.708730,False,True,False,False,False,False,True,False,False,False,True
535,33.895315,121.886093,81.707230,False,True,False,False,True,False,False,False,True,False,False
695,27.212401,68.172309,65.951614,False,False,False,False,False,True,False,False,False,False,True
557,15.575654,411.028470,54.978284,False,False,True,False,False,True,False,False,False,False,True
836,33.296918,128.095746,89.662751,True,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,23.207658,396.242019,82.858963,False,False,True,False,True,False,False,True,False,False,False
270,31.187223,694.981886,45.211240,False,False,False,False,False,True,False,True,False,False,False
860,30.510552,776.447446,83.338518,False,False,False,False,False,False,False,False,False,False,False
435,29.019383,29.973590,59.474095,False,False,False,False,False,False,True,False,False,False,False
102,21.287120,883.785885,47.897741,True,False,False,False,True,False,False,True,False,False,False

In [12]:
X_test_OHE

,temperature,rainfall,humidity,soil_type_Loamy,soil_type_Peaty,soil_type_Sandy,soil_type_Silty,weather_condition_Rainy,weather_condition_Stormy,weather_condition_Sunny,crop_type_Corn,crop_type_Rice,crop_type_Soybeans,crop_type_Wheat
521,22.617817,934.436027,46.721756,False,False,True,False,False,False,True,False,False,True,False
737,31.331989,194.622512,67.224117,False,False,False,False,True,False,False,False,False,True,False
740,24.253596,827.537896,58.284037,False,False,True,False,False,False,False,False,False,False,False
660,22.121935,600.594333,63.614090,False,True,False,False,True,False,False,False,True,False,False
411,34.001239,111.919619,47.027648,True,False,False,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
408,33.107640,585.354364,89.401798,False,False,False,True,False,False,False,True,False,False,False
332,15.287870,228.454741,70.189773,True,False,False,False,False,False,False,False,False,True,False
208,15.101232,273.626666,54.610912,False,True,False,False,True,False,False,False,False,True,False
613,16.635181,324.333753,77.045203,False,False,False,True,False,False,False,False,True,False,False
78,22.169315,218.253888,89.249483,False,False,False,True,True,False,False,False,False,True,False

In [13]:
from category_encoders import LeaveOneOutEncoder

In [14]:
LOOE = LeaveOneOutEncoder(cols=["soil_type", "weather_condition", "crop_type"])
X_train_LOOE = LOOE.fit_transform(X_train, y_train) 
X_test_LOOE = LOOE.transform(X_test)

In [15]:
X_train_LOOE

,temperature,rainfall,humidity,soil_type,weather_condition,crop_type
29,15.929008,828.915474,72.708730,5.947070,5.800713,6.145453
535,33.895315,121.886093,81.707230,5.977010,5.792711,5.936277
695,27.212401,68.172309,65.951614,5.646986,5.902408,6.142703
557,15.575654,411.028470,54.978284,6.020760,5.923666,6.168956
836,33.296918,128.095746,89.662751,5.980224,6.093390,5.620369
...,...,...,...,...,...,...
106,23.207658,396.242019,82.858963,6.024408,5.790415,5.650135
270,31.187223,694.981886,45.211240,5.680502,5.926932,5.650489
860,30.510552,776.447446,83.338518,5.636295,6.082929,5.869557
435,29.019383,29.973590,59.474095,5.633901,5.787198,5.867046
102,21.287120,883.785885,47.897741,6.000956,5.784653,5.642068

In [16]:
X_test_LOOE

,temperature,rainfall,humidity,soil_type,weather_condition,crop_type
521,22.617817,934.436027,46.721756,6.006902,5.810522,5.880593
737,31.331989,194.622512,67.224117,5.662720,5.777420,5.880593
740,24.253596,827.537896,58.284037,6.006902,6.100385,5.895647
660,22.121935,600.594333,63.614090,5.956709,5.777420,5.917129
411,34.001239,111.919619,47.027648,5.989928,5.777420,5.880593
...,...,...,...,...,...,...
408,33.107640,585.354364,89.401798,5.868918,6.100385,5.632905
332,15.287870,228.454741,70.189773,5.989928,6.100385,5.880593
208,15.101232,273.626666,54.610912,5.956709,5.777420,5.880593
613,16.635181,324.333753,77.045203,5.868918,6.100385,5.917129
78,22.169315,218.253888,89.249483,5.868918,5.777420,5.880593

In [17]:
with open("LOOE.pkl","wb") as f:
  pickle.dump(LOOE, f)
with open("LOOE.pkl","rb") as f:
  loaded_encoder_LOOE = pickle.load(f)
loaded_encoder_LOOE

LeaveOneOutEncoder(cols=['soil_type', 'weather_condition', 'crop_type'])

In [18]:
print(len(df), len(df.columns))
print()
print(df.columns)

1000 7

Index(['temperature', 'rainfall', 'humidity', 'soil_type', 'weather_condition',
       'crop_type', 'yield'],
      dtype='object')

In [19]:
df_clean = df.dropna(axis=0)
df_clean = df_clean.dropna(axis=1)
df_clean = df_clean.dropna(subset=["temperature", "rainfall"])
print(len(df_clean), len(df_clean.columns))

1000 7

In [20]:
scaler_std = StandardScaler()

In [21]:
X_train_OHE_scaled = scaler_std.fit_transform(X_train_OHE[["temperature", "rainfall", "humidity"]])
X_test_OHE_scaled = scaler_std.transform(X_test_OHE[["temperature", "rainfall", "humidity"]])

In [22]:
# X_train_OHE_scaled

In [23]:
with open("OHE_scaled.pkl","wb") as f:
  pickle.dump(scaler_std, f)

In [24]:
with open("OHE_scaled.pkl","rb") as f:
  loaded_encoder_OHE_scaled = pickle.load(f)

In [25]:
loaded_encoder_OHE_scaled

StandardScaler()

In [26]:
numeric_columns = ["temperature", "rainfall", "humidity"]

In [27]:
X_train_OHE_scaled_df = pd.DataFrame(X_train_OHE_scaled, columns=numeric_columns)
X_train_OHE_scaled_df

     temperature  rainfall  humidity
0      -1.534059  1.077829  0.507474
1       1.536054 -1.345349  1.129535
2       0.394066 -1.529440  0.040357
3      -1.594441 -0.354381 -0.718223
4       1.433799 -1.324067  1.679497
..           ...       ...       ...
795    -0.290271 -0.405058  1.209154
796     1.073291  0.618803 -1.393414
797     0.957660  0.898007  1.242305
798     0.702846 -1.660358 -0.407430
799    -0.618456  1.265885 -1.207698

[800 rows x 3 columns]

In [28]:
X_test_OHE_scaled_df = pd.DataFrame(X_test_OHE_scaled, columns=numeric_columns)
X_test_OHE_scaled_df

     temperature  rainfall  humidity
0      -0.391064  1.439477 -1.288993
1       1.098028 -1.096062  0.128325
2      -0.111540  1.073108 -0.489698
3      -0.475801  0.295312 -0.121234
4       1.554155 -1.379507 -1.267847
..           ...       ...       ...
195     1.401455  0.243081  1.661457
196    -1.643618 -0.980110  0.333339
197    -1.675511 -0.825293 -0.743620
198    -1.413387 -0.651507  0.807252
199    -0.467705 -1.015071  1.650928

[200 rows x 3 columns]

In [29]:
final_train_OHE_scaled = pd.concat([X_train_OHE_scaled_df, X_train_OHE.drop(columns=numeric_columns)], axis=1)
final_train_OHE_scaled

,temperature,rainfall,humidity,soil_type_Loamy,soil_type_Peaty,soil_type_Sandy,soil_type_Silty,weather_condition_Rainy,weather_condition_Stormy,weather_condition_Sunny,crop_type_Corn,crop_type_Rice,crop_type_Soybeans,crop_type_Wheat
0,-1.534059,1.077829,0.507474,False,False,True,False,False,False,True,False,False,False,False
1,1.536054,-1.345349,1.129535,True,False,False,False,False,False,True,True,False,False,False
2,0.394066,-1.529440,0.040357,False,True,False,False,True,False,False,False,False,False,True
3,-1.594441,-0.354381,-0.718223,False,False,True,False,False,False,True,False,False,True,False
4,1.433799,-1.324067,1.679497,False,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
856,NaN,NaN,NaN,False,False,False,False,False,False,True,False,False,True,False
955,NaN,NaN,NaN,False,True,False,False,True,False,False,False,False,True,False
805,NaN,NaN,NaN,False,False,False,True,False,False,False,False,False,False,False
871,NaN,NaN,NaN,False,False,True,False,False,False,False,False,False,False,False
860,NaN,NaN,NaN,False,False,False,False,False,False,False,False,False,False,False

In [30]:
final_test_OHE_scaled = pd.concat([X_test_OHE_scaled_df, X_test_OHE.drop(columns=numeric_columns)], axis=1)
final_test_OHE_scaled

,temperature,rainfall,humidity,soil_type_Loamy,soil_type_Peaty,soil_type_Sandy,soil_type_Silty,weather_condition_Rainy,weather_condition_Stormy,weather_condition_Sunny,crop_type_Corn,crop_type_Rice,crop_type_Soybeans,crop_type_Wheat
0,-0.391064,1.439477,-1.288993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.098028,-1.096062,0.128325,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-0.111540,1.073108,-0.489698,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-0.475801,0.295312,-0.121234,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.554155,-1.379507,-1.267847,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213,NaN,NaN,NaN,False,False,False,False,False,False,False,False,False,True,False
408,NaN,NaN,NaN,False,False,False,True,False,False,False,True,False,False,False
332,NaN,NaN,NaN,True,False,False,False,False,False,False,False,False,True,False
208,NaN,NaN,NaN,False,True,False,False,True,False,False,False,False,True,False
613,NaN,NaN,NaN,False,False,False,True,False,False,False,False,True,False,False

In [31]:
final_train_OHE_scaled["split"]="train"
final_test_OHE_scaled["split"]="test"

In [32]:
final_OHE_scaled = pd.concat([final_train_OHE_scaled, final_test_OHE_scaled], axis=0)
final_OHE_scaled

,temperature,rainfall,humidity,soil_type_Loamy,soil_type_Peaty,soil_type_Sandy,soil_type_Silty,weather_condition_Rainy,weather_condition_Stormy,weather_condition_Sunny,crop_type_Corn,crop_type_Rice,crop_type_Soybeans,crop_type_Wheat,split
0,-1.534059,1.077829,0.507474,False,False,True,False,False,False,True,False,False,False,False,train
1,1.536054,-1.345349,1.129535,True,False,False,False,False,False,True,True,False,False,False,train
2,0.394066,-1.529440,0.040357,False,True,False,False,True,False,False,False,False,False,True,train
3,-1.594441,-0.354381,-0.718223,False,False,True,False,False,False,True,False,False,True,False,train
4,1.433799,-1.324067,1.679497,False,False,False,False,False,True,False,False,False,False,False,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213,NaN,NaN,NaN,False,False,False,False,False,False,False,False,False,True,False,test
408,NaN,NaN,NaN,False,False,False,True,False,False,False,True,False,False,False,test
332,NaN,NaN,NaN,True,False,False,False,False,False,False,False,False,True,False,test
208,NaN,NaN,NaN,False,True,False,False,True,False,False,False,False,True,False,test
613,NaN,NaN,NaN,False,False,False,True,False,False,False,False,True,False,False,test

In [33]:
final_OHE_scaled.to_csv("/Users/mrnan/OneDrive/Desktop/AgriYield/final_OHE_scaled.csv", index=False)

In [34]:
df_loaded_OHE = pd.read_csv("/Users/mrnan/OneDrive/Desktop/AgriYield/final_OHE_scaled.csv")

In [35]:
scaler_std = StandardScaler()
X_train_LOOE_scaled = scaler_std.fit_transform(X_train_LOOE[["temperature","rainfall", "humidity"]])
X_test_LOOE_scaled = scaler_std.transform(X_test_LOOE[["temperature","rainfall", "humidity"]])

In [36]:
with open("LOOE_scaled.pkl","wb") as f:
  pickle.dump(scaler_std, f)
with open("LOOE_scaled.pkl","rb") as f:
  loaded_encoder_LOOE_scaled = pickle.load(f)
loaded_encoder_LOOE_scaled

StandardScaler()

In [37]:
X_train_LOOE_scaled_df = pd.DataFrame(X_train_LOOE_scaled, columns=numeric_columns)
X_train_LOOE_scaled_df

     temperature  rainfall  humidity
0      -1.534059  1.077829  0.507474
1       1.536054 -1.345349  1.129535
2       0.394066 -1.529440  0.040357
3      -1.594441 -0.354381 -0.718223
4       1.433799 -1.324067  1.679497
..           ...       ...       ...
795    -0.290271 -0.405058  1.209154
796     1.073291  0.618803 -1.393414
797     0.957660  0.898007  1.242305
798     0.702846 -1.660358 -0.407430
799    -0.618456  1.265885 -1.207698

[800 rows x 3 columns]

In [38]:
X_test_LOOE_scaled_df = pd.DataFrame(X_test_LOOE_scaled, columns=numeric_columns)
X_test_LOOE_scaled_df

     temperature  rainfall  humidity
0      -0.391064  1.439477 -1.288993
1       1.098028 -1.096062  0.128325
2      -0.111540  1.073108 -0.489698
3      -0.475801  0.295312 -0.121234
4       1.554155 -1.379507 -1.267847
..           ...       ...       ...
195     1.401455  0.243081  1.661457
196    -1.643618 -0.980110  0.333339
197    -1.675511 -0.825293 -0.743620
198    -1.413387 -0.651507  0.807252
199    -0.467705 -1.015071  1.650928

[200 rows x 3 columns]

In [39]:
final_train_LOOE_scaled = pd.concat([X_train_LOOE_scaled_df, X_train_LOOE.drop(columns=numeric_columns)], axis=1)
final_train_LOOE_scaled

     temperature  rainfall  humidity  soil_type  weather_condition  crop_type
0      -1.534059  1.077829  0.507474   6.025766           5.827235   5.917163
1       1.536054 -1.345349  1.129535   5.977035           5.798211   5.617030
2       0.394066 -1.529440  0.040357   5.936989           5.760885   6.135311
3      -1.594441 -0.354381 -0.718223   5.995419           5.798584   5.867755
4       1.433799 -1.324067  1.679497   5.658721           5.910994   5.893081
..           ...       ...       ...        ...                ...        ...
856          NaN       NaN       NaN   5.686372           5.831168   5.903982
955          NaN       NaN       NaN   5.967183           5.784896   5.890984
805          NaN       NaN       NaN   5.841951           6.081239   5.867170
871          NaN       NaN       NaN   5.989904           6.086627   5.874781
860          NaN       NaN       NaN   5.636295           6.082929   5.869557

[956 rows x 6 columns]

In [40]:
final_test_LOOE_scaled = pd.concat([X_test_LOOE_scaled_df, X_test_LOOE.drop(columns=numeric_columns)], axis=1)
final_test_LOOE_scaled

     temperature  rainfall  humidity  soil_type  weather_condition  crop_type
0      -0.391064  1.439477 -1.288993        NaN                NaN        NaN
1       1.098028 -1.096062  0.128325        NaN                NaN        NaN
2      -0.111540  1.073108 -0.489698        NaN                NaN        NaN
3      -0.475801  0.295312 -0.121234        NaN                NaN        NaN
4       1.554155 -1.379507 -1.267847        NaN                NaN        NaN
..           ...       ...       ...        ...                ...        ...
213          NaN       NaN       NaN   5.662720           6.100385   5.880593
408          NaN       NaN       NaN   5.868918           6.100385   5.632905
332          NaN       NaN       NaN   5.989928           6.100385   5.880593
208          NaN       NaN       NaN   5.956709           5.777420   5.880593
613          NaN       NaN       NaN   5.868918           6.100385   5.917129

[367 rows x 6 columns]

In [41]:
final_train_LOOE_scaled["split"]="train"
final_test_LOOE_scaled["split"]="test"

In [42]:
final_LOOE_scaled = pd.concat([final_train_LOOE_scaled, final_test_LOOE_scaled], axis=0)
final_LOOE_scaled

,temperature,rainfall,humidity,soil_type,weather_condition,crop_type,split
0,-1.534059,1.077829,0.507474,6.025766,5.827235,5.917163,train
1,1.536054,-1.345349,1.129535,5.977035,5.798211,5.617030,train
2,0.394066,-1.529440,0.040357,5.936989,5.760885,6.135311,train
3,-1.594441,-0.354381,-0.718223,5.995419,5.798584,5.867755,train
4,1.433799,-1.324067,1.679497,5.658721,5.910994,5.893081,train
...,...,...,...,...,...,...,...
213,NaN,NaN,NaN,5.662720,6.100385,5.880593,test
408,NaN,NaN,NaN,5.868918,6.100385,5.632905,test
332,NaN,NaN,NaN,5.989928,6.100385,5.880593,test
208,NaN,NaN,NaN,5.956709,5.777420,5.880593,test
613,NaN,NaN,NaN,5.868918,6.100385,5.917129,test

In [43]:
final_LOOE_scaled.to_csv("/Users/mrnan/OneDrive/Desktop/AgriYield/final_LOOE_scaled.csv", index=False)

In [44]:
df_loaded_LOOE = pd.read_csv("/Users/mrnan/OneDrive/Desktop/AgriYield/final_LOOE_scaled.csv")

In [45]:
scaler_MM = MinMaxScaler()

X_train_OHE_scaled_MM = scaler_MM.fit_transform(X_train_OHE[["temperature", "rainfall", "humidity"]])
X_test_OHE_scaled_MM = scaler_MM.transform(X_test_OHE[["temperature", "rainfall", "humidity"]])

In [46]:
with open("OHE_scaled_MM.pkl","wb") as f:
  pickle.dump(scaler_std, f)
with open("OHE_scaled_MM.pkl","rb") as f:
  loaded_encoder_OHE_scaled_MM = pickle.load(f)
loaded_encoder_OHE_scaled_MM

StandardScaler()

In [47]:
X_train_OHE_scaled_MM

array([[0.04202491, 0.8288506 , 0.65666461],
       [0.94477667, 0.11912103, 0.83772755],
       [0.60898076, 0.06520211, 0.52070157],
       ...,
       [0.77470275, 0.7761822 , 0.87055145],
       [0.69977605, 0.02685751, 0.39036443],
       [0.31125357, 0.88393057, 0.1574313 ]], shape=(800, 3))

In [48]:
X_train_LOOE_scaled_MM = scaler_MM.fit_transform(X_train_LOOE[["temperature", "rainfall", "humidity"]])
X_test_LOOE_scaled_MM = scaler_MM.transform(X_test_LOOE[["temperature", "rainfall", "humidity"]])

In [49]:
with open("LOOE_scaled_MM.pkl","wb") as f:
  pickle.dump(scaler_std, f)
with open("LOOE_scaled_MM.pkl","rb") as f:
  loaded_encoder_LOOE_scaled_MM = pickle.load(f)
loaded_encoder_LOOE_scaled_MM

StandardScaler()

In [50]:
X_train_OHE_scaled_MM_df = pd.DataFrame(X_train_OHE_scaled_MM, columns=numeric_columns, index=X_train_OHE.index)
print(type(X_train_OHE_scaled_MM))
X_train_OHE_scaled_MM_df

<class 'numpy.ndarray'>

     temperature  rainfall  humidity
29      0.042025  0.828851  0.656665
535     0.944777  0.119121  0.837728
695     0.608981  0.065202  0.520702
557     0.024270  0.409368  0.299902
836     0.914709  0.125354  0.997804
..           ...       ...       ...
106     0.407755  0.394525  0.860902
270     0.808703  0.694406  0.103375
860     0.774703  0.776182  0.870551
435     0.699776  0.026858  0.390364
102     0.311254  0.883931  0.157431

[800 rows x 3 columns]

In [51]:
X_test_OHE_scaled_MM_df = pd.DataFrame(X_test_LOOE_scaled_MM, columns=numeric_columns, index=X_test_OHE.index)
print(type(X_train_OHE_scaled_MM))
X_test_OHE_scaled_MM_df

<class 'numpy.ndarray'>

     temperature  rainfall  humidity
521     0.378117  0.934774  0.133769
737     0.815977  0.192135  0.546306
740     0.460310  0.827468  0.366419
660     0.353200  0.599657  0.473667
411     0.950099  0.109116  0.139924
..           ...       ...       ...
408     0.905198  0.584359  0.992554
332     0.009810  0.226097  0.605980
208     0.000432  0.271441  0.292510
613     0.077508  0.322342  0.743921
78      0.355581  0.215857  0.989489

[200 rows x 3 columns]

In [52]:
X_train_LOOE_scaled_MM_df = pd.DataFrame(X_train_LOOE_scaled_MM, columns=numeric_columns)
X_train_LOOE_scaled_MM_df

     temperature  rainfall  humidity
0       0.042025  0.828851  0.656665
1       0.944777  0.119121  0.837728
2       0.608981  0.065202  0.520702
3       0.024270  0.409368  0.299902
4       0.914709  0.125354  0.997804
..           ...       ...       ...
795     0.407755  0.394525  0.860902
796     0.808703  0.694406  0.103375
797     0.774703  0.776182  0.870551
798     0.699776  0.026858  0.390364
799     0.311254  0.883931  0.157431

[800 rows x 3 columns]

In [53]:
X_test_LOOE_scaled_MM_df = pd.DataFrame(X_test_LOOE_scaled_MM, columns=numeric_columns)
X_test_LOOE_scaled_MM_df

     temperature  rainfall  humidity
0       0.378117  0.934774  0.133769
1       0.815977  0.192135  0.546306
2       0.460310  0.827468  0.366419
3       0.353200  0.599657  0.473667
4       0.950099  0.109116  0.139924
..           ...       ...       ...
195     0.905198  0.584359  0.992554
196     0.009810  0.226097  0.605980
197     0.000432  0.271441  0.292510
198     0.077508  0.322342  0.743921
199     0.355581  0.215857  0.989489

[200 rows x 3 columns]

In [54]:
final_train_OHE_scaled_MM = pd.concat([X_train_OHE_scaled_MM_df, X_train_OHE.drop(columns=numeric_columns)], axis=1)
final_train_OHE_scaled_MM

,temperature,rainfall,humidity,soil_type_Loamy,soil_type_Peaty,soil_type_Sandy,soil_type_Silty,weather_condition_Rainy,weather_condition_Stormy,weather_condition_Sunny,crop_type_Corn,crop_type_Rice,crop_type_Soybeans,crop_type_Wheat
29,0.042025,0.828851,0.656665,False,True,False,False,False,False,True,False,False,False,True
535,0.944777,0.119121,0.837728,False,True,False,False,True,False,False,False,True,False,False
695,0.608981,0.065202,0.520702,False,False,False,False,False,True,False,False,False,False,True
557,0.024270,0.409368,0.299902,False,False,True,False,False,True,False,False,False,False,True
836,0.914709,0.125354,0.997804,True,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,0.407755,0.394525,0.860902,False,False,True,False,True,False,False,True,False,False,False
270,0.808703,0.694406,0.103375,False,False,False,False,False,True,False,True,False,False,False
860,0.774703,0.776182,0.870551,False,False,False,False,False,False,False,False,False,False,False
435,0.699776,0.026858,0.390364,False,False,False,False,False,False,True,False,False,False,False
102,0.311254,0.883931,0.157431,True,False,False,False,True,False,False,True,False,False,False

In [55]:
final_test_OHE_scaled_MM = pd.concat([X_test_OHE_scaled_MM_df, X_test_OHE.drop(columns=numeric_columns)], axis=1)
final_test_OHE_scaled_MM

,temperature,rainfall,humidity,soil_type_Loamy,soil_type_Peaty,soil_type_Sandy,soil_type_Silty,weather_condition_Rainy,weather_condition_Stormy,weather_condition_Sunny,crop_type_Corn,crop_type_Rice,crop_type_Soybeans,crop_type_Wheat
521,0.378117,0.934774,0.133769,False,False,True,False,False,False,True,False,False,True,False
737,0.815977,0.192135,0.546306,False,False,False,False,True,False,False,False,False,True,False
740,0.460310,0.827468,0.366419,False,False,True,False,False,False,False,False,False,False,False
660,0.353200,0.599657,0.473667,False,True,False,False,True,False,False,False,True,False,False
411,0.950099,0.109116,0.139924,True,False,False,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
408,0.905198,0.584359,0.992554,False,False,False,True,False,False,False,True,False,False,False
332,0.009810,0.226097,0.605980,True,False,False,False,False,False,False,False,False,True,False
208,0.000432,0.271441,0.292510,False,True,False,False,True,False,False,False,False,True,False
613,0.077508,0.322342,0.743921,False,False,False,True,False,False,False,False,True,False,False
78,0.355581,0.215857,0.989489,False,False,False,True,True,False,False,False,False,True,False

In [56]:
final_train_LOOE_scaled_MM = pd.concat([X_train_LOOE_scaled_MM_df, X_train_LOOE.drop(columns=numeric_columns)], axis=1)
final_train_LOOE_scaled_MM

     temperature  rainfall  humidity  soil_type  weather_condition  crop_type
0       0.042025  0.828851  0.656665   6.025766           5.827235   5.917163
1       0.944777  0.119121  0.837728   5.977035           5.798211   5.617030
2       0.608981  0.065202  0.520702   5.936989           5.760885   6.135311
3       0.024270  0.409368  0.299902   5.995419           5.798584   5.867755
4       0.914709  0.125354  0.997804   5.658721           5.910994   5.893081
..           ...       ...       ...        ...                ...        ...
856          NaN       NaN       NaN   5.686372           5.831168   5.903982
955          NaN       NaN       NaN   5.967183           5.784896   5.890984
805          NaN       NaN       NaN   5.841951           6.081239   5.867170
871          NaN       NaN       NaN   5.989904           6.086627   5.874781
860          NaN       NaN       NaN   5.636295           6.082929   5.869557

[956 rows x 6 columns]

In [57]:
final_test_LOOE_scaled_MM = pd.concat([X_test_LOOE_scaled_MM_df, X_test_LOOE.drop(columns=numeric_columns)], axis=1)
final_test_LOOE_scaled_MM

     temperature  rainfall  humidity  soil_type  weather_condition  crop_type
0       0.378117  0.934774  0.133769        NaN                NaN        NaN
1       0.815977  0.192135  0.546306        NaN                NaN        NaN
2       0.460310  0.827468  0.366419        NaN                NaN        NaN
3       0.353200  0.599657  0.473667        NaN                NaN        NaN
4       0.950099  0.109116  0.139924        NaN                NaN        NaN
..           ...       ...       ...        ...                ...        ...
213          NaN       NaN       NaN   5.662720           6.100385   5.880593
408          NaN       NaN       NaN   5.868918           6.100385   5.632905
332          NaN       NaN       NaN   5.989928           6.100385   5.880593
208          NaN       NaN       NaN   5.956709           5.777420   5.880593
613          NaN       NaN       NaN   5.868918           6.100385   5.917129

[367 rows x 6 columns]

In [58]:
with open("scaler.pkl", "wb") as f:
    pickle.dump(scaler_MM, f)

with open("scaler.pkl", "rb") as f:
    loaded_scaler = pickle.load(f)

In [59]:
final_train_OHE_scaled_MM["split"]="train"
final_test_OHE_scaled_MM["split"]="test"

In [60]:
final_train_OHE_scaled_MM

,temperature,rainfall,humidity,soil_type_Loamy,soil_type_Peaty,soil_type_Sandy,soil_type_Silty,weather_condition_Rainy,weather_condition_Stormy,weather_condition_Sunny,crop_type_Corn,crop_type_Rice,crop_type_Soybeans,crop_type_Wheat,split
29,0.042025,0.828851,0.656665,False,True,False,False,False,False,True,False,False,False,True,train
535,0.944777,0.119121,0.837728,False,True,False,False,True,False,False,False,True,False,False,train
695,0.608981,0.065202,0.520702,False,False,False,False,False,True,False,False,False,False,True,train
557,0.024270,0.409368,0.299902,False,False,True,False,False,True,False,False,False,False,True,train
836,0.914709,0.125354,0.997804,True,False,False,False,False,False,False,True,False,False,False,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,0.407755,0.394525,0.860902,False,False,True,False,True,False,False,True,False,False,False,train
270,0.808703,0.694406,0.103375,False,False,False,False,False,True,False,True,False,False,False,train
860,0.774703,0.776182,0.870551,False,False,False,False,False,False,False,False,False,False,False,train
435,0.699776,0.026858,0.390364,False,False,False,False,False,False,True,False,False,False,False,train
102,0.311254,0.883931,0.157431,True,False,False,False,True,False,False,True,False,False,False,train

In [61]:
final_OHE_scaled_MM = pd.concat([final_train_OHE_scaled_MM, final_test_OHE_scaled_MM], axis=0)
final_OHE_scaled_MM

,temperature,rainfall,humidity,soil_type_Loamy,soil_type_Peaty,soil_type_Sandy,soil_type_Silty,weather_condition_Rainy,weather_condition_Stormy,weather_condition_Sunny,crop_type_Corn,crop_type_Rice,crop_type_Soybeans,crop_type_Wheat,split
29,0.042025,0.828851,0.656665,False,True,False,False,False,False,True,False,False,False,True,train
535,0.944777,0.119121,0.837728,False,True,False,False,True,False,False,False,True,False,False,train
695,0.608981,0.065202,0.520702,False,False,False,False,False,True,False,False,False,False,True,train
557,0.024270,0.409368,0.299902,False,False,True,False,False,True,False,False,False,False,True,train
836,0.914709,0.125354,0.997804,True,False,False,False,False,False,False,True,False,False,False,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
408,0.905198,0.584359,0.992554,False,False,False,True,False,False,False,True,False,False,False,test
332,0.009810,0.226097,0.605980,True,False,False,False,False,False,False,False,False,True,False,test
208,0.000432,0.271441,0.292510,False,True,False,False,True,False,False,False,False,True,False,test
613,0.077508,0.322342,0.743921,False,False,False,True,False,False,False,False,True,False,False,test
78,0.355581,0.215857,0.989489,False,False,False,True,True,False,False,False,False,True,False,test

In [62]:
final_OHE_scaled_MM.to_csv("/Users/mrnan/OneDrive/Desktop/AgriYield/final_OHE_scaled_MM.csv", index=False)

In [63]:
df_loaded = pd.read_csv("/Users/mrnan/OneDrive/Desktop/AgriYield/final_OHE_scaled_MM.csv")

In [64]:
final_LOOE_scaled_MM = pd.concat([final_train_LOOE_scaled_MM, final_test_LOOE_scaled_MM], axis=0)
final_LOOE_scaled_MM

     temperature  rainfall  humidity  soil_type  weather_condition  crop_type
0       0.042025  0.828851  0.656665   6.025766           5.827235   5.917163
1       0.944777  0.119121  0.837728   5.977035           5.798211   5.617030
2       0.608981  0.065202  0.520702   5.936989           5.760885   6.135311
3       0.024270  0.409368  0.299902   5.995419           5.798584   5.867755
4       0.914709  0.125354  0.997804   5.658721           5.910994   5.893081
..           ...       ...       ...        ...                ...        ...
213          NaN       NaN       NaN   5.662720           6.100385   5.880593
408          NaN       NaN       NaN   5.868918           6.100385   5.632905
332          NaN       NaN       NaN   5.989928           6.100385   5.880593
208          NaN       NaN       NaN   5.956709           5.777420   5.880593
613          NaN       NaN       NaN   5.868918           6.100385   5.917129

[1323 rows x 6 columns]

In [65]:
final_LOOE_scaled_MM.to_csv("/Users/mrnan/OneDrive/Desktop/AgriYield/final_LOOE_scaled_MM.csv", index=False)

In [66]:
df_loaded_LOOE_MM = pd.read_csv("/Users/mrnan/OneDrive/Desktop/AgriYield/final_LOOE_scaled_MM.csv")

In [67]:
train_loaded_df = df_loaded[df_loaded["split"] == "train"].drop(columns="split")
test_loaded_df = df_loaded[df_loaded["split"] == "test"].drop(columns="split")

In [68]:
train_loaded_df

,temperature,rainfall,humidity,soil_type_Loamy,soil_type_Peaty,soil_type_Sandy,soil_type_Silty,weather_condition_Rainy,weather_condition_Stormy,weather_condition_Sunny,crop_type_Corn,crop_type_Rice,crop_type_Soybeans,crop_type_Wheat
0,0.042025,0.828851,0.656665,False,True,False,False,False,False,True,False,False,False,True
1,0.944777,0.119121,0.837728,False,True,False,False,True,False,False,False,True,False,False
2,0.608981,0.065202,0.520702,False,False,False,False,False,True,False,False,False,False,True
3,0.024270,0.409368,0.299902,False,False,True,False,False,True,False,False,False,False,True
4,0.914709,0.125354,0.997804,True,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,0.407755,0.394525,0.860902,False,False,True,False,True,False,False,True,False,False,False
796,0.808703,0.694406,0.103375,False,False,False,False,False,True,False,True,False,False,False
797,0.774703,0.776182,0.870551,False,False,False,False,False,False,False,False,False,False,False
798,0.699776,0.026858,0.390364,False,False,False,False,False,False,True,False,False,False,False
799,0.311254,0.883931,0.157431,True,False,False,False,True,False,False,True,False,False,False

In [69]:
test_loaded_df

,temperature,rainfall,humidity,soil_type_Loamy,soil_type_Peaty,soil_type_Sandy,soil_type_Silty,weather_condition_Rainy,weather_condition_Stormy,weather_condition_Sunny,crop_type_Corn,crop_type_Rice,crop_type_Soybeans,crop_type_Wheat
800,0.378117,0.934774,0.133769,False,False,True,False,False,False,True,False,False,True,False
801,0.815977,0.192135,0.546306,False,False,False,False,True,False,False,False,False,True,False
802,0.460310,0.827468,0.366419,False,False,True,False,False,False,False,False,False,False,False
803,0.353200,0.599657,0.473667,False,True,False,False,True,False,False,False,True,False,False
804,0.950099,0.109116,0.139924,True,False,False,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.905198,0.584359,0.992554,False,False,False,True,False,False,False,True,False,False,False
996,0.009810,0.226097,0.605980,True,False,False,False,False,False,False,False,False,True,False
997,0.000432,0.271441,0.292510,False,True,False,False,True,False,False,False,False,True,False
998,0.077508,0.322342,0.743921,False,False,False,True,False,False,False,False,True,False,False
999,0.355581,0.215857,0.989489,False,False,False,True,True,False,False,False,False,True,False

In [70]:
final_train_OHE_scaled_MM["rainfall_temp_ratio"] = final_train_OHE_scaled_MM["rainfall"]/final_train_OHE_scaled_MM["temperature"]

In [71]:
from sklearn.ensemble import RandomForestRegressor

model_se = RandomForestRegressor(n_estimators=100, random_state=42, criterion='squared_error')
model_se = RandomForestRegressor(n_estimators=100, random_state=42, criterion='absolute_error')

model_se.fit(train_loaded_df, y_train)

RandomForestRegressor(criterion='absolute_error', random_state=42)

In [72]:
y_preds = model_se.predict(test_loaded_df)

In [73]:
from sklearn.metrics import mean_squared_error

test_mse = mean_squared_error(y_true=y_test, y_pred = y_preds)

print(test_mse)

5.162301689971221

In [74]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, r2_score

In [75]:
final_train_OHE_scaled["split"]="train"
final_test_OHE_scaled["split"]="test"

In [76]:
datasets = {
    "OHE + StandardScaler": (final_train_OHE_scaled, final_test_OHE_scaled),
    "OHE + MinMaxScaler": (final_train_OHE_scaled_MM, final_test_OHE_scaled_MM),
    "LOOE + StandardScaler": (final_train_LOOE_scaled, final_test_LOOE_scaled),
    "LOOE + MinMaxScaler": (final_train_LOOE_scaled_MM, final_test_LOOE_scaled_MM)
}

In [77]:
models = {
    "Linear Regression": LinearRegression(),
    "K-Nearest Neighbors": KNeighborsRegressor(),
    "Random Forest": RandomForestRegressor(n_estimators=100, random_state=42),
    "Support Vector Regressor (SVR)": SVR()
}

In [78]:
for data_name, (X_train_df, X_test_df) in datasets.items():
    print(f"Dataset: {data_name}")
    print("-" * (len(data_name) + 10))
    
    try:
        clean_train_indices = X_train_df.replace([np.inf, -np.inf], np.nan).dropna().index
        
        X_train_clean = X_train_df.loc[clean_train_indices].drop(columns='split', errors='ignore')
        y_train_clean = y_train.loc[clean_train_indices]

        clean_test_indices = X_test_df.replace([np.inf, -np.inf], np.nan).dropna().index
        X_test_clean = X_test_df.loc[clean_test_indices].drop(columns='split', errors='ignore')
        y_test_clean = y_test.loc[clean_test_indices]
            
        for model_name, model in models.items():
            model.fit(X_train_clean, y_train_clean)
            y_preds = model.predict(X_test_clean)
            mse = mean_squared_error(y_test_clean, y_preds)
            r2 = r2_score(y_test_clean, y_preds)
            print(f"  -> {model_name}:")
            print(f"     - MSE: {mse:.4f}")
            print(f"     - R2: {r2:.4f}")
        print("\n" + "="*50 + "\n")
    except Exception as e:
        print(f"An error occurred while processing {data_name} dataset: {e}")
        print("\n" + "="*50 + "\n")

Dataset: OHE + StandardScaler
------------------------------
  -> Linear Regression:
     - MSE: 5.4628
     - R2: -0.0196
  -> K-Nearest Neighbors:
     - MSE: 5.6063
     - R2: -0.0463
  -> Random Forest:
     - MSE: 5.7461
     - R2: -0.0724
  -> Support Vector Regressor (SVR):
     - MSE: 5.7434
     - R2: -0.0719

==================================================

Dataset: OHE + MinMaxScaler
----------------------------
An error occurred while processing OHE + MinMaxScaler dataset: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- rainfall_temp_ratio


==================================================

Dataset: LOOE + StandardScaler
-------------------------------
  -> Linear Regression:
     - MSE: 5.3784
     - R2: -0.0038
  -> K-Nearest Neighbors:
     - MSE: 6.3680
     - R2: -0.1885
  -> Random Forest:
     - MSE: 5.5668
     - R2: -0.0390
  -> Support Vector Regressor (SVR):
     - MSE: 5.4369
     - R2: -0.0147

==================================================

Dataset: LOOE + MinMaxScaler
-----------------------------
  -> Linear Regression:
     - MSE: 5.3784
     - R2: -0.0038
  -> K-Nearest Neighbors:
     - MSE: 8.2716
     - R2: -0.5438
  -> Random Forest:
     - MSE: 5.5668
     - R2: -0.0390
  -> Support Vector Regressor (SVR):
     - MSE: 5.4028
     - R2: -0.0084

==================================================

In [79]:
sample=pd.DataFrame([{
  "temperature":30,
  "rainfall":550,
  "humidity":75,
  "soil_type":"Sandy",
  "weather_condition":"Sunny",
  "crop_type":"Corn"
}])

In [80]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [81]:
categorical_features = ["soil_type", "weather_condition", "crop_type"]
numeric_features = ["temperature", "rainfall","humidity"]

In [82]:
preprocessor = ColumnTransformer(
    transformers=[
        ("categorical_encoding", OneHotEncoder(drop="first", handle_unknown="ignore", sparse_output=False), categorical_features),
        ("numerical_scaling", StandardScaler(), numeric_features)
    ],
    remainder='passthrough'
)

In [83]:
pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", LinearRegression())
])

In [84]:
# Fit the pipeline on the training data
pipeline.fit(X_train, y_train)

# Export the pipeline using pickle
with open("pipeline.pkl", "wb") as f:
    pickle.dump(pipeline, f)

# Load the pipeline back (optional, for demonstration)
with open("pipeline.pkl", "rb") as f:
    loaded_pipeline = pickle.load(f)

# Predict using the loaded pipeline for the sample data
prediction = loaded_pipeline.predict(sample)
print(f"The predicted yield for your sample data is: {prediction[0]:.4f} tons/hectare")

The predicted yield for your sample data is: 5.6058 tons/hectare

In [85]:
loaded_pipeline

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('categorical_encoding',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['soil_type',
                                                   'weather_condition',
                                                   'crop_type']),
                                                 ('numerical_scaling',
                                                  StandardScaler(),
                                                  ['temperature', 'rainfall',
                                                   'humidity'])])),
                ('model', LinearRegression())])

In [86]:
pipeline.fit(X_train, y_train)
prediction = pipeline.predict(sample)

print(f"The predicted yield for your sample data is: {prediction[0]:.4f} tons/hectare")

The predicted yield for your sample data is: 5.6058 tons/hectare

In [87]:

X_train_LOOE_scaled_std = scaler_std.fit_transform(X_train_LOOE[numeric_columns])
X_test_LOOE_scaled_std = scaler_std.transform(X_test_LOOE[numeric_columns])

final_train_LOOE_scaled = pd.concat([pd.DataFrame(X_train_LOOE_scaled_std, columns=numeric_columns, index=X_train_LOOE.index), X_train_LOOE.drop(columns=numeric_columns)], axis=1)
final_test_LOOE_scaled = pd.concat([pd.DataFrame(X_test_LOOE_scaled_std, columns=numeric_columns, index=X_test_LOOE.index), X_test_LOOE.drop(columns=numeric_columns)], axis=1)

model = LinearRegression()

clean_train_indices = final_train_LOOE_scaled.replace([np.inf, -np.inf], np.nan).dropna().index
X_train_clean = final_train_LOOE_scaled.loc[clean_train_indices]
y_train_clean = y_train.loc[clean_train_indices]

clean_test_indices = final_test_LOOE_scaled.replace([np.inf, -np.inf], np.nan).dropna().index
X_test_clean = final_test_LOOE_scaled.loc[clean_test_indices]
y_test_clean = y_test.loc[clean_test_indices]

model.fit(X_train_clean, y_train_clean)
predictions = model.predict(X_test_clean)

print("Predicted yields for every row in the LOOE + StandardScaler test dataset:")
print(predictions)

results_df = X_test.loc[clean_test_indices].copy()
results_df['predicted_yield'] = predictions
results_df['actual_yield'] = y_test_clean
print("\nOriginal test data with predicted and actual yields:")
print(results_df.head())

Predicted yields for every row in the LOOE + StandardScaler test dataset:
[5.77285093 6.27449929 5.57456457 5.93979484 5.74149952 5.69437141
 5.67980684 5.69709456 6.05191031 5.802565   6.26299096 5.41369944
 6.02082927 5.77770352 6.17903545 6.02228094 5.76942212 5.75699948
 5.87346158 5.90684354 5.69865462 5.95712299 6.37593646 5.99595742
 6.01117628 5.79248445 6.25176596 5.63871113 5.81178479 5.90127915
 5.78158767 6.00563242 5.76929727 5.9839993  6.06988407 5.81845535
 6.3217029  5.86340873 6.02721724 5.79537989 5.66065681 6.2187254
 6.14599267 5.82292741 6.10099101 5.88147922 5.97082686 6.15167636
 5.8178737  5.82898518 5.78810102 6.03474286 5.69131653 5.91886253
 5.5803782  5.53381066 5.92561383 5.89342121 5.77923406 5.99156782
 5.69326316 6.09520563 6.05708177 6.15547514 6.1909439  5.51315093
 6.21438547 6.04146074 6.30338418 5.9067588  5.69746531 6.37041351
 6.03896031 6.25001129 6.18322836 5.77186773 5.74448047 5.89545207
 5.97542047 5.91814196 5.93254389 5.74052042 5.88754267 5.65358705
 5.79879228 5.80815623 5.76200444 5.69148107 6.15756667 6.05687901
 6.23973667 6.10308811 5.89141504 5.87188601 6.15571431 6.09556949
 5.88843864 6.348402   5.63606487 5.94740967 5.71335619 6.05548913
 5.93347158 5.89388239 5.96883756 6.14391729 5.81162902 5.91958487
 6.12383673 6.29131966 6.27673605 5.7938818  5.95981565 5.71145577
 5.53372353 5.70051889 5.81697751 6.332186   5.74857841 5.99405099
 6.17399513 5.98966889 6.01395045 5.9211563  5.89787551 5.66076144
 5.78493508 5.71229298 6.26443475 5.93074805 5.82869397 5.46342558
 5.86479945 6.08002225 5.65274254 6.10495759 5.68451441 5.60458175
 5.77986914 5.90194919 6.30431501 5.87274634 5.74980609 5.6833166
 6.09915338 5.6220405  5.51109523 5.85685084 6.26033487 5.91771326
 6.33652903 6.00448881 6.03201688 6.15914922 6.21313968 6.05288047
 5.76241004 5.82310335 5.55139818 5.81604647 5.80838278 5.65088868
 5.68027933 6.25906038 5.67604602 6.15417382 5.5109909  5.61437383
 5.71142963 5.85931835 5.98700764 6.00030067 6.15817286 5.7725697
 5.9681899  5.73927025 6.15782285 6.176189   5.86294401 6.23489937
 5.72741587 6.47595909 6.08009245 5.85952233 5.61010912 5.86003313
 5.41774246 5.91869421 5.81145783 6.12624239 5.53530474 5.91339561
 5.69063323 5.98927476 6.20043227 5.89770852 5.76327391 5.99693974
 5.91945723 6.18803159]

Original test data with predicted and actual yields:
     temperature    rainfall   humidity soil_type weather_condition crop_type  \
521    22.617817  934.436027  46.721756     Sandy             Sunny  Soybeans
737    31.331989  194.622512  67.224117      Clay             Rainy  Soybeans
740    24.253596  827.537896  58.284037     Sandy            Cloudy    Barley
660    22.121935  600.594333  63.614090     Peaty             Rainy      Rice
411    34.001239  111.919619  47.027648     Loamy             Rainy  Soybeans

     predicted_yield  actual_yield
521         5.772851      9.144910
737         6.274499      9.858048
740         5.574565      4.813761
660         5.939795      5.309648
411         5.741500      5.485377